name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - name: Print a greeting
        env:
          HELLO_WORLD: Hello World!
        run:
          echo $HELLO_WORLD
