name: Release

# workflow's trigger
on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

# workflow's jobs
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ macos-latest, windows-latest, ubuntu-latest ]
        os: [ windows-latest ]

    # release steps
    steps:
      # step 1: check out repository
      - name: Check out Git repository
        uses: actions/checkout@v2

      # step 2: install node env
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # step 3: yarn install
      - name: Yarn install
        run:
          yarn install

      # step 4: build app for mac/win/linux
      - name: Build mac app
        if: matrix.os == 'macos-latest'
        run: |
          npm run make
      - name: Build win app
        if: matrix.os == 'windows-latest'
        run: |
          npm run make
      - name: Build linux app
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run make

      # step 5: cleanup artifacts
      - name: Cleanup artifacts for macos
        if: matrix.os == 'macos-latest'
        run: |
          mkdir artifacts
          mv out/make/zip/darwin/*/*.zip artifacts || true
      - name: Cleanup artifacts for win
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
        # mv out/make/**/*.zip artifacts || true
      - name: Cleanup artifacts for linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir artifacts
        # mv out/make/ artifacts || true

      # step 6: upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts

      # step 7: release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
